# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Wprowadzenie',   url: 'introduction.html'}
- {name: 'Archiwum wpisów', url: 'archive.html'}
- {name: 'Kontakt', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fa-brands fa-github',     link: 'https://www.github.com/tempus-barbaricum'}
- {icon: 'fa-brands fa-x-twitter',    link: 'https://x.com'}
- {icon: 'fa-brands fa-facebook',   link: 'http://www.facebook.com'}
#- {icon: 'envelope',   link: 'mailto:xd@gmail.com'}
- {icon: 'fa-solid fa-square-rss', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Nowsze'
  previous_page: 'Starsze'

sharing_button_prompt: 'Podziel się!'

related_posts: 'Mogą się spodobać:'

post_date_prefix: 'Napisane'
